### ISSUE TITLE
Does not work under Meteor 0.6 +

### ISSUE THREAD

**Issue by stephentcannon** [jhoxray/meteor-mongo-extensions#1]
Your package is awesome and I have been using it for sometime.

It does not work on Meteor 0.6 + versions.

I made these changes in the server file in an attempt to get it to work
  #path = **meteor_bootstrap**.require("path")
  path = Npm.require("path")
  #MongoDB = **meteor_bootstrap**.require("mongodb")
  MongoDB = Npm.require("mongodb")
  #Future = **meteor_bootstrap**.require(path.join("fibers", "future"))
  Future = Npm.require(path.join("fibers", "future"))

but I am getting these errors.

Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object._.each.Npm.require (/home/steeve/etherpos/etherpos/.meteor/local/build/server/server.js:241:20)
    at app/server/aggregate.coffee.js:5:15
    at /home/steeve/etherpos/etherpos/.meteor/local/build/server/server.js:286:12
    at Array.forEach (native)
    at Function._.each._.forEach (/home/steeve/.meteor/tools/275efdf2db/lib/node_modules/underscore/underscore.js:79:11)
    at run (/home/steeve/etherpos/etherpos/.meteor/local/build/server/server.js:227:7)

I am going to keep playing around with it to see if I can get it to work.  

Just wanted to make you aware.

**Comment by stephentcannon** [comment]
Just to give you an update.  I left this commented out
#MongoDB = Npm.require("mongodb")

and aggregation you wrote is working fine still.

**Comment by jhoxray** [comment]
Fixed.
